export const SUBJECT_PRESET_HINTS = Object.freeze({
  'data-body': 'Mediciones editoriales y marcas sobre el cuerpo en movimiento.',
  fragment: 'Desprende partes del sujeto siguiendo su movimiento.',
  echo: 'Copias temporales de la silueta desplazadas por el movimiento.',
  smear: 'Arrastra temporalmente píxeles del cuerpo.',
  anatomy: 'Tracking corporal técnico y estructural.',
  scan: 'Barridos y contorno sobre la silueta detectada.',
  dissolve: 'Transición entre cuerpo real y representación digital.',
});

export const SUBJECT_BASIC_CONTROLS = Object.freeze({
  anatomy: ['amount', 'reactivity', 'density'],
  'data-body': ['amount', 'reactivity', 'density'],
  fragment: ['amount', 'reactivity', 'density', 'persistence', 'scale'],
  echo: ['amount', 'reactivity', 'persistence'],
  smear: ['amount', 'reactivity', 'persistence'],
  scan: ['amount', 'reactivity', 'density'],
  dissolve: ['amount', 'reactivity', 'scale'],
});

export const SUBJECT_PRESET_IDS = Object.freeze([
  'data-body',
  'fragment',
  'echo',
  'smear',
  'anatomy',
  'scan',
  'dissolve',
]);

export const SUBJECT_PRESET_LABELS = Object.freeze({
  'data-body': 'DATA BODY',
  fragment: 'FRAGMENT',
  echo: 'ECHO',
  smear: 'SMEAR',
  anatomy: 'ANATOMY',
  scan: 'SCAN',
  dissolve: 'DISSOLVE',
});

const baseModules = (overrides = {}) => ({
  bodyMap: {
    showSkeleton: true,
    showJoints: true,
    showLabels: false,
    showCoordinates: false,
    showVelocity: false,
    showBoundingBox: false,
    showCenter: false,
    connectionOpacity: 0.48,
    lineThickness: 1,
    labelSize: 9,
    density: 0.45,
    color: '#f0f0ec',
    ...overrides.bodyMap,
  },
  fragments: {
    enabled: false,
    density: 0.45,
    spread: 0.35,
    sizeMin: 8,
    sizeMax: 32,
    persistence: 0.5,
    motionInfluence: 0.75,
    beatInfluence: 0.4,
    ...overrides.fragments,
  },
  trails: {
    enabled: false,
    mode: 'body',
    copies: 5,
    spacing: 0.08,
    decay: 0.72,
    opacity: 0.28,
    motionInfluence: 0.65,
    ...overrides.trails,
  },
  smear: {
    enabled: false,
    spread: 0.38,
    decay: 0.8,
    threshold: 0.1,
    motionInfluence: 0.85,
    beatInfluence: 0.25,
    subjectOnly: true,
    ...overrides.smear,
  },
  scan: {
    enabled: false,
    lineDensity: 0.4,
    threshold: 0.38,
    posterize: 4,
    outline: true,
    blocks: false,
    ...overrides.scan,
  },
  pixelBody: {
    enabled: false,
    gridSize: 16,
    threshold: 0.32,
    dissolve: 0.55,
    ...overrides.pixelBody,
  },
  rgb: {
    enabled: false,
    split: 1.2,
    jitter: 0.12,
    slices: 5,
    displacement: 0.15,
    ...overrides.rgb,
  },
});

export const SUBJECT_PRESETS = Object.freeze({
  anatomy: Object.freeze({
    amount: 0.58,
    reactivity: 'motion',
    density: 0.38,
    persistence: 0.42,
    scale: 0.95,
    color: '#f0f0ec',
    seed: 18412,
    motionInfluence: 0.65,
    beatInfluence: 0.3,
    modules: baseModules({
      bodyMap: {
        showSkeleton: true,
        showJoints: true,
        showLabels: true,
        showCoordinates: true,
        showVelocity: true,
        showCenter: true,
        connectionOpacity: 0.52,
        density: 0.42,
      },
    }),
  }),
  fragment: Object.freeze({
    amount: 0.68,
    reactivity: 'motion',
    density: 0.52,
    persistence: 0.58,
    scale: 1,
    color: '#f0f0ec',
    seed: 30102,
    motionInfluence: 0.88,
    beatInfluence: 0.45,
    modules: baseModules({
      bodyMap: { showSkeleton: false, showJoints: false, showLabels: false },
      fragments: {
        enabled: true,
        density: 0.58,
        spread: 0.42,
        sizeMin: 10,
        sizeMax: 36,
        persistence: 0.62,
        motionInfluence: 0.9,
      },
      rgb: { enabled: true, split: 0.8, jitter: 0.1 },
    }),
  }),
  smear: Object.freeze({
    amount: 0.72,
    reactivity: 'motion',
    density: 0.45,
    persistence: 0.68,
    scale: 1,
    color: '#f0f0ec',
    seed: 52004,
    motionInfluence: 0.92,
    beatInfluence: 0.35,
    modules: baseModules({
      bodyMap: { showSkeleton: false, showLabels: false, showJoints: false },
      smear: {
        enabled: true,
        spread: 0.44,
        decay: 0.76,
        threshold: 0.06,
        motionInfluence: 0.95,
        subjectOnly: true,
      },
      rgb: { enabled: true, split: 1, jitter: 0.12 },
    }),
  }),
  echo: Object.freeze({
    amount: 0.64,
    reactivity: 'motion-beat',
    density: 0.42,
    persistence: 0.62,
    scale: 1,
    color: '#ececea',
    seed: 41003,
    motionInfluence: 0.72,
    beatInfluence: 0.55,
    modules: baseModules({
      bodyMap: {
        showSkeleton: true,
        showLabels: false,
        connectionOpacity: 0.35,
        density: 0.3,
      },
      trails: {
        enabled: true,
        mode: 'body',
        copies: 6,
        spacing: 0.09,
        decay: 0.7,
        opacity: 0.34,
        motionInfluence: 0.78,
      },
    }),
  }),
  'data-body': Object.freeze({
    amount: 0.62,
    reactivity: 'motion-beat',
    density: 0.48,
    persistence: 0.46,
    scale: 1,
    color: '#d8d8d4',
    seed: 22041,
    motionInfluence: 0.78,
    beatInfluence: 0.52,
    modules: baseModules({
      bodyMap: {
        showSkeleton: false,
        showJoints: false,
        showLabels: true,
        showCoordinates: false,
        showVelocity: true,
        showBoundingBox: false,
        density: 0.55,
        connectionOpacity: 0.35,
      },
      fragments: {
        enabled: true,
        density: 0.22,
        spread: 0.18,
        sizeMin: 6,
        sizeMax: 18,
        persistence: 0.4,
      },
      scan: { enabled: true, lineDensity: 0.32, blocks: false, outline: true },
    }),
  }),
  scan: Object.freeze({
    amount: 0.58,
    reactivity: 'beat',
    density: 0.4,
    persistence: 0.4,
    scale: 1,
    color: '#e8e8e4',
    seed: 63005,
    motionInfluence: 0.3,
    beatInfluence: 0.72,
    modules: baseModules({
      bodyMap: {
        showSkeleton: true,
        showLabels: false,
        density: 0.28,
        connectionOpacity: 0.38,
      },
      scan: {
        enabled: true,
        lineDensity: 0.48,
        outline: true,
        blocks: true,
      },
    }),
  }),
  dissolve: Object.freeze({
    amount: 0.66,
    reactivity: 'motion-beat',
    density: 0.5,
    persistence: 0.52,
    scale: 1,
    color: '#f0f0ec',
    seed: 74006,
    motionInfluence: 0.68,
    beatInfluence: 0.58,
    modules: baseModules({
      bodyMap: { showSkeleton: false, showLabels: false },
      fragments: {
        enabled: true,
        density: 0.32,
        spread: 0.28,
        sizeMin: 8,
        sizeMax: 22,
        persistence: 0.48,
      },
      pixelBody: {
        enabled: true,
        gridSize: 14,
        dissolve: 0.68,
        threshold: 0.3,
      },
      rgb: { enabled: true, split: 0.9, jitter: 0.08 },
    }),
  }),
});
